- name: apt key for vscode
  apt_key: url=https://packages.microsoft.com/keys/microsoft.asc state=present
- name: apt repo for vscode
  apt_repository: repo="deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" update_cache=yes filename="vscode"

- name: install vscode
  apt:
    state: present
    pkg: code

# Install extensions:
- name: make sure vscode extension directory exists
  file: path=/opt/vscode/extensions state=directory
  
- name: vscode extensions
  shell: code --extensions-dir /opt/vscode/extensions --user-data-dir /opt/vscode --no-sandbox --install-extension {{ item }}
  loop: "{{ vscode_extensions }}"

- name: create a script to symlink our extensions
  copy:
    dest: /usr/local/bin/vscode-extension-install
    mode: 0755
    content: |
      #!/bin/bash
      mkdir -p $HOME/.vscode
      ln -sf /opt/vscode/extensions $HOME/.vscode/extensions

- name: Ensure Python 3 is installed
  apt:
    name: python3
    state: present
  become: yes

- name: Copy the ext_slayer.py script to the VM
  copy:
    src: "{{ playbook_dir }}/files/scripts/ext_slayer.py"
    dest: /usr/local/bin/ext_slayer.py
    mode: '0755'
  become: yes

- name: Run ext_slayer.py to mark extensions as disabled
  become: yes
  shell: |
    sudo -u contestant env HOME=/home/contestant \
      python3 /usr/local/bin/ext_slayer.py